language: python

python:

  - '3.6.7'

# safelist

branches:

  only:

    - staging


before_script:

  - pip install -r requirements.txt


env: DJANGO_SETTINGS_MODULE="pur_beurre.travis_settings"

services:

  - postgresql

addons:
  postgresql: "9.5"

script:

  - python manage.py test