# Generated by Django 2.0 on 2018-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20181029_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('n_grade', models.CharField(max_length=2)),
                ('category', models.CharField(max_length=250)),
                ('img_nutrition', models.URLField(default='0000000')),
                ('store', models.CharField(default='0000000', max_length=250)),
            ],
            options={
                'verbose_name': 'product',
            },
        ),
    ]
