# Generated by Django 2.0 on 2018-11-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_auto_20181113_0852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
