# Generated by Django 2.0 on 2018-11-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_auto_20181119_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
